### ISSUE TITLE
希望能支持 RN

### ISSUE THREAD

**Issue by zisheng-ai** [ant-design/ant-design-mobile-chart#1]
这个库是在编写中，保持高度关注

**Comment by cycgit** [comment]
@youngjuning RN目前没有计划支持。 ant-design-mobile-chart 仅支持web。

**Comment by zisheng-ai** [comment]
那太遗憾了，现在社区也只有一款封装百度的可以用

**Comment by dxq613** [comment]
加油！！！

**Comment by BANG88** [comment]
@youngjuning https://github.com/wuxudong/react-native-charts-wrapper

**Comment by zisheng-ai** [comment]
@bang88 https://github.com/tomLadder/react-native-echarts-wrapper 这个更棒
